{% set name = "mutatest" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3b3d12893f53255e92af6191945ff667d754aa2f304c4f0dfe62f7aa2caf2d1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
      - mutatest = mutatest.cli:cli_main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - coverage >=4.4,<6.0
    - typing-extensions

test:
  imports:
    - mutatest
  requires:
    - coverage >=4.4,<6.0
    - pytest
    - freezegun
    - hypothesis
    - pytest-cov
  source_files:
    - pytest.ini
  commands:
    - pytest --pyargs mutatest
    - mutatest -h

about:
  home: https://github.com/EvanKepner/mutatest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python mutation testing: test your tests!'
  description: |
    Are you confident in your tests?
    Try out mutatest and see if your tests will detect small modifications (mutations) in the code.
    Surviving mutations represent subtle changes that are undetectable by your tests.
    Mutatest modifies the pycache, not your source code, and has multiple running modes.
  doc_url: https://mutatest.readthedocs.io/
  dev_url: https://github.com/EvanKepner/mutatest

extra:
  recipe-maintainers:
    - EvanKepner
